EXTRAFLAGS += -flto
OLED_ENABLE     = yes
OLED_DRIVER     = ssd1306
MOUSEKEY_ENABLE = no     # Mouse keys
VIA_ENABLE      = yes    # Enable VIA
LTO_ENABLE      = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
WPM_ENABLE      = yes
